/**
 * ملف البيانات الأولية للأطر التنظيمية السعودية
 * Saudi Regulatory Frameworks Seed Data
 * 
 * هذا الملف يحتوي على البيانات الأساسية للأطر التنظيمية السعودية الرئيسية:
 * 1. نظام حماية البيانات الشخصية (PDPL)
 * 2. الضوابط الأساسية للأمن السيبراني (ECC)
 * 3. نظام مكافحة غسل الأموال (AML/CFT)
 * 4. نظام المدفوعات وخدماتها
 * 5. تعليمات مختبر التقنية المالية
 * 6. قواعد التمويل الجماعي بالدين
 * 7. نظام الشركات الجديد
 */

import { InsertFramework, InsertControl } from '../drizzle/schema';

/**
 * الأطر التنظيمية الرئيسية
 */
export const frameworks: Omit<InsertFramework, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    code: 'PDPL',
    name: 'Personal Data Protection Law',
    nameAr: 'نظام حماية البيانات الشخصية',
    description: 'The Personal Data Protection Law (PDPL) regulates the processing of personal data in Saudi Arabia, ensuring the protection of individuals\' privacy and personal information.',
    descriptionAr: 'نظام حماية البيانات الشخصية ينظم معالجة البيانات الشخصية في المملكة العربية السعودية، ويضمن حماية خصوصية الأفراد ومعلوماتهم الشخصية.',
    issuingAuthority: 'Saudi Data & AI Authority (SDAIA)',
    issuingAuthorityAr: 'الهيئة السعودية للبيانات والذكاء الاصطناعي (سدايا)',
    effectiveDate: new Date('2023-03-14'),
    version: '1.0',
    applicableSectors: ['financial_services', 'technology', 'healthcare', 'retail', 'government', 'education'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://sdaia.gov.sa/ar/PDPL/Pages/default.aspx',
    officialWebsite: 'https://sdaia.gov.sa',
    status: 'active',
    displayOrder: 1,
  },
  {
    code: 'ECC',
    name: 'Essential Cybersecurity Controls',
    nameAr: 'الضوابط الأساسية للأمن السيبراني',
    description: 'The Essential Cybersecurity Controls (ECC) framework consists of 114 controls designed to protect critical infrastructure and sensitive information from cyber threats.',
    descriptionAr: 'إطار الضوابط الأساسية للأمن السيبراني يتكون من 114 ضابطاً مصممة لحماية البنية التحتية الحرجة والمعلومات الحساسة من التهديدات السيبرانية.',
    issuingAuthority: 'National Cybersecurity Authority (NCA)',
    issuingAuthorityAr: 'الهيئة الوطنية للأمن السيبراني',
    effectiveDate: new Date('2018-01-01'),
    version: '2.0',
    applicableSectors: ['financial_services', 'technology', 'healthcare', 'government'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://nca.gov.sa/pages/ecc.html',
    officialWebsite: 'https://nca.gov.sa',
    status: 'active',
    displayOrder: 2,
  },
  {
    code: 'AML_CFT',
    name: 'Anti-Money Laundering and Counter-Terrorism Financing',
    nameAr: 'نظام مكافحة غسل الأموال وتمويل الإرهاب',
    description: 'The AML/CFT framework imposes strict obligations on financial institutions and designated non-financial businesses to prevent money laundering and terrorism financing.',
    descriptionAr: 'إطار مكافحة غسل الأموال وتمويل الإرهاب يفرض التزامات صارمة على المؤسسات المالية والأعمال والمهن غير المالية المحددة لمنع غسل الأموال وتمويل الإرهاب.',
    issuingAuthority: 'Saudi Central Bank (SAMA)',
    issuingAuthorityAr: 'البنك المركزي السعودي (ساما)',
    effectiveDate: new Date('2017-11-05'),
    version: '1.0',
    applicableSectors: ['financial_services'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://www.sama.gov.sa/en-US/Laws/Pages/BankingRulesLaws.aspx',
    officialWebsite: 'https://www.sama.gov.sa',
    status: 'active',
    displayOrder: 3,
  },
  {
    code: 'PSL',
    name: 'Payment Services Law',
    nameAr: 'نظام المدفوعات وخدماتها',
    description: 'The Payment Services Law regulates payment services in Saudi Arabia, ensuring the stability of the financial system and protecting payment service users.',
    descriptionAr: 'نظام المدفوعات وخدماتها ينظم خدمات المدفوعات في المملكة العربية السعودية، ويضمن استقرار النظام المالي وحماية مستخدمي خدمات المدفوعات.',
    issuingAuthority: 'Saudi Central Bank (SAMA)',
    issuingAuthorityAr: 'البنك المركزي السعودي (ساما)',
    effectiveDate: new Date('2019-04-16'),
    version: '1.0',
    applicableSectors: ['financial_services'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://www.sama.gov.sa/en-US/Laws/Pages/PaymentSystemsLaw.aspx',
    officialWebsite: 'https://www.sama.gov.sa',
    status: 'active',
    displayOrder: 4,
  },
  {
    code: 'FINTECH_SANDBOX',
    name: 'Fintech Sandbox Instructions',
    nameAr: 'تعليمات مختبر التقنية المالية',
    description: 'The Fintech Sandbox provides a controlled environment for testing innovative financial services under regulatory supervision.',
    descriptionAr: 'مختبر التقنية المالية يوفر بيئة محكومة لاختبار الخدمات المالية المبتكرة تحت الإشراف التنظيمي.',
    issuingAuthority: 'Capital Market Authority (CMA)',
    issuingAuthorityAr: 'هيئة السوق المالية',
    effectiveDate: new Date('2018-06-01'),
    version: '1.0',
    applicableSectors: ['financial_services', 'technology'],
    mandatory: false,
    relatedFrameworks: [],
    documentUrl: 'https://cma.org.sa/en/RulesRegulations/Regulations/Pages/default.aspx',
    officialWebsite: 'https://cma.org.sa',
    status: 'active',
    displayOrder: 5,
  },
  {
    code: 'CROWDFUNDING',
    name: 'Debt Crowdfunding Rules',
    nameAr: 'قواعد التمويل الجماعي بالدين',
    description: 'The Debt Crowdfunding Rules regulate crowdfunding platforms that facilitate debt-based financing.',
    descriptionAr: 'قواعد التمويل الجماعي بالدين تنظم منصات التمويل الجماعي التي تسهل التمويل القائم على الدين.',
    issuingAuthority: 'Capital Market Authority (CMA)',
    issuingAuthorityAr: 'هيئة السوق المالية',
    effectiveDate: new Date('2019-01-01'),
    version: '1.0',
    applicableSectors: ['financial_services'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://cma.org.sa/en/RulesRegulations/Regulations/Pages/default.aspx',
    officialWebsite: 'https://cma.org.sa',
    status: 'active',
    displayOrder: 6,
  },
  {
    code: 'COMPANIES_LAW',
    name: 'Companies Law',
    nameAr: 'نظام الشركات',
    description: 'The Companies Law regulates the establishment and management of companies in Saudi Arabia.',
    descriptionAr: 'نظام الشركات ينظم تأسيس وإدارة الشركات في المملكة العربية السعودية.',
    issuingAuthority: 'Ministry of Commerce',
    issuingAuthorityAr: 'وزارة التجارة',
    effectiveDate: new Date('2023-01-19'),
    version: '2.0',
    applicableSectors: ['financial_services', 'technology', 'healthcare', 'retail', 'education', 'other'],
    mandatory: true,
    relatedFrameworks: [],
    documentUrl: 'https://mc.gov.sa/en/regulations/Pages/default.aspx',
    officialWebsite: 'https://mc.gov.sa',
    status: 'active',
    displayOrder: 7,
  },
];

/**
 * ضوابط نظام حماية البيانات الشخصية (PDPL)
 * المبادئ الأساسية والمتطلبات الرئيسية
 */
export const pdplControls: Omit<InsertControl, 'id' | 'frameworkId' | 'createdAt' | 'updatedAt'>[] = [
  {
    code: 'PDPL-1.1',
    title: 'Lawfulness and Transparency',
    titleAr: 'الشرعية والشفافية',
    description: 'Personal data must be processed lawfully and transparently, with the data subject being informed.',
    descriptionAr: 'يجب معالجة البيانات الشخصية بطرق مشروعة وشفافة مع إعلام صاحب البيانات.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'critical',
    implementationGuidance: 'Establish clear data processing policies and provide privacy notices to data subjects.',
    implementationGuidanceAr: 'وضع سياسات واضحة لمعالجة البيانات وتقديم إشعارات الخصوصية لأصحاب البيانات.',
    evidenceRequirements: ['Privacy Policy', 'Privacy Notices', 'Consent Forms'],
    testingProcedures: ['Review privacy policy', 'Verify consent mechanisms', 'Check transparency of data processing'],
    tags: ['privacy', 'transparency', 'lawfulness'],
    displayOrder: 1,
  },
  {
    code: 'PDPL-1.2',
    title: 'Purpose Limitation',
    titleAr: 'تحديد الغرض',
    description: 'Personal data must be collected for specified, explicit, and legitimate purposes only.',
    descriptionAr: 'يجب جمع البيانات الشخصية لأغراض محددة وصريحة ومشروعة فقط.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'critical',
    implementationGuidance: 'Document the specific purposes for data collection and ensure data is not used for incompatible purposes.',
    implementationGuidanceAr: 'توثيق الأغراض المحددة لجمع البيانات والتأكد من عدم استخدام البيانات لأغراض غير متوافقة.',
    evidenceRequirements: ['Data Processing Register', 'Purpose Documentation'],
    testingProcedures: ['Review data collection purposes', 'Verify purpose limitation controls'],
    tags: ['purpose', 'limitation', 'data-collection'],
    displayOrder: 2,
  },
  {
    code: 'PDPL-1.3',
    title: 'Data Minimization',
    titleAr: 'التناسب',
    description: 'Only collect personal data that is necessary and proportionate to the stated purpose.',
    descriptionAr: 'جمع البيانات الشخصية الضرورية فقط والمتناسبة مع الغرض المحدد.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'high',
    implementationGuidance: 'Implement data minimization controls and regularly review data collection practices.',
    implementationGuidanceAr: 'تطبيق ضوابط تقليل البيانات ومراجعة ممارسات جمع البيانات بانتظام.',
    evidenceRequirements: ['Data Minimization Policy', 'Data Collection Forms'],
    testingProcedures: ['Review data fields collected', 'Verify necessity of each data element'],
    tags: ['minimization', 'proportionality'],
    displayOrder: 3,
  },
  {
    code: 'PDPL-1.4',
    title: 'Accuracy',
    titleAr: 'الدقة',
    description: 'Personal data must be accurate and kept up to date.',
    descriptionAr: 'يجب أن تكون البيانات الشخصية دقيقة ومحدثة.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'high',
    implementationGuidance: 'Implement mechanisms to ensure data accuracy and allow data subjects to update their information.',
    implementationGuidanceAr: 'تطبيق آليات لضمان دقة البيانات والسماح لأصحاب البيانات بتحديث معلوماتهم.',
    evidenceRequirements: ['Data Accuracy Procedures', 'Data Update Mechanisms'],
    testingProcedures: ['Review data accuracy controls', 'Test data update functionality'],
    tags: ['accuracy', 'data-quality'],
    displayOrder: 4,
  },
  {
    code: 'PDPL-1.5',
    title: 'Storage Limitation',
    titleAr: 'تقييد الاحتفاظ',
    description: 'Personal data must not be kept longer than necessary for the purpose.',
    descriptionAr: 'يجب عدم الاحتفاظ بالبيانات الشخصية لمدة أطول من اللازم للغرض.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'high',
    implementationGuidance: 'Define data retention periods and implement automated deletion mechanisms.',
    implementationGuidanceAr: 'تحديد فترات الاحتفاظ بالبيانات وتطبيق آليات الحذف التلقائي.',
    evidenceRequirements: ['Data Retention Policy', 'Deletion Procedures'],
    testingProcedures: ['Review retention periods', 'Verify deletion mechanisms'],
    tags: ['retention', 'deletion'],
    displayOrder: 5,
  },
  {
    code: 'PDPL-1.6',
    title: 'Confidentiality and Security',
    titleAr: 'السرية والأمان',
    description: 'Personal data must be protected from unauthorized access, disclosure, or loss.',
    descriptionAr: 'يجب حماية البيانات الشخصية من الوصول غير المصرح به أو الإفصاح أو الفقدان.',
    category: 'Data Processing Principles',
    categoryAr: 'مبادئ معالجة البيانات',
    priority: 'critical',
    implementationGuidance: 'Implement technical and organizational security measures to protect personal data.',
    implementationGuidanceAr: 'تطبيق التدابير الأمنية التقنية والتنظيمية لحماية البيانات الشخصية.',
    evidenceRequirements: ['Security Policy', 'Access Controls', 'Encryption Mechanisms'],
    testingProcedures: ['Review security controls', 'Test access controls', 'Verify encryption'],
    tags: ['security', 'confidentiality', 'encryption'],
    displayOrder: 6,
  },
  {
    code: 'PDPL-2.1',
    title: 'Right to Access',
    titleAr: 'الحق في الوصول',
    description: 'Data subjects have the right to access their personal data held by the controller.',
    descriptionAr: 'لأصحاب البيانات الحق في الوصول إلى بياناتهم الشخصية المحفوظة لدى المتحكم.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'high',
    implementationGuidance: 'Establish procedures for data subjects to request access to their data.',
    implementationGuidanceAr: 'وضع إجراءات لأصحاب البيانات لطلب الوصول إلى بياناتهم.',
    evidenceRequirements: ['Access Request Procedures', 'Data Subject Portal'],
    testingProcedures: ['Test access request process', 'Verify data provided to subjects'],
    tags: ['rights', 'access', 'transparency'],
    displayOrder: 7,
  },
  {
    code: 'PDPL-2.2',
    title: 'Right to Rectification',
    titleAr: 'الحق في التصحيح',
    description: 'Data subjects have the right to correct inaccurate or incomplete personal data.',
    descriptionAr: 'لأصحاب البيانات الحق في تصحيح البيانات الشخصية غير الدقيقة أو غير الكاملة.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'high',
    implementationGuidance: 'Provide mechanisms for data subjects to update or correct their data.',
    implementationGuidanceAr: 'توفير آليات لأصحاب البيانات لتحديث أو تصحيح بياناتهم.',
    evidenceRequirements: ['Data Update Procedures', 'Correction Mechanisms'],
    testingProcedures: ['Test data correction process', 'Verify updates are applied'],
    tags: ['rights', 'correction', 'accuracy'],
    displayOrder: 8,
  },
  {
    code: 'PDPL-2.3',
    title: 'Right to Erasure',
    titleAr: 'الحق في المحو',
    description: 'Data subjects have the right to request deletion of their personal data in certain circumstances.',
    descriptionAr: 'لأصحاب البيانات الحق في طلب حذف بياناتهم الشخصية في ظروف معينة.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'high',
    implementationGuidance: 'Establish procedures for processing erasure requests and verify legal grounds.',
    implementationGuidanceAr: 'وضع إجراءات لمعالجة طلبات المحو والتحقق من الأسس القانونية.',
    evidenceRequirements: ['Erasure Request Procedures', 'Deletion Logs'],
    testingProcedures: ['Test erasure request process', 'Verify data is deleted'],
    tags: ['rights', 'erasure', 'deletion'],
    displayOrder: 9,
  },
  {
    code: 'PDPL-2.4',
    title: 'Right to Data Portability',
    titleAr: 'الحق في نقل البيانات',
    description: 'Data subjects have the right to receive their personal data in a portable format.',
    descriptionAr: 'لأصحاب البيانات الحق في الحصول على بياناتهم الشخصية بصيغة قابلة للنقل.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'medium',
    implementationGuidance: 'Provide data export functionality in commonly used formats (CSV, JSON, etc.).',
    implementationGuidanceAr: 'توفير وظيفة تصدير البيانات بصيغ شائعة الاستخدام (CSV، JSON، إلخ).',
    evidenceRequirements: ['Data Export Functionality', 'Portability Procedures'],
    testingProcedures: ['Test data export process', 'Verify format compatibility'],
    tags: ['rights', 'portability', 'export'],
    displayOrder: 10,
  },
  {
    code: 'PDPL-2.5',
    title: 'Right to Object',
    titleAr: 'الحق في الاعتراض',
    description: 'Data subjects have the right to object to certain types of data processing.',
    descriptionAr: 'لأصحاب البيانات الحق في الاعتراض على أنواع معينة من معالجة البيانات.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'medium',
    implementationGuidance: 'Establish procedures for handling objections and stopping relevant processing.',
    implementationGuidanceAr: 'وضع إجراءات للتعامل مع الاعتراضات وإيقاف المعالجة ذات الصلة.',
    evidenceRequirements: ['Objection Procedures', 'Processing Cessation Records'],
    testingProcedures: ['Test objection process', 'Verify processing is stopped'],
    tags: ['rights', 'objection', 'consent'],
    displayOrder: 11,
  },
  {
    code: 'PDPL-2.6',
    title: 'Right to Withdraw Consent',
    titleAr: 'الحق في سحب الموافقة',
    description: 'Data subjects have the right to withdraw consent for data processing at any time.',
    descriptionAr: 'لأصحاب البيانات الحق في سحب الموافقة على معالجة البيانات في أي وقت.',
    category: 'Data Subject Rights',
    categoryAr: 'حقوق أصحاب البيانات',
    priority: 'high',
    implementationGuidance: 'Provide easy mechanisms for withdrawing consent and stop processing accordingly.',
    implementationGuidanceAr: 'توفير آليات سهلة لسحب الموافقة وإيقاف المعالجة وفقاً لذلك.',
    evidenceRequirements: ['Consent Withdrawal Mechanisms', 'Processing Cessation Records'],
    testingProcedures: ['Test consent withdrawal process', 'Verify processing stops'],
    tags: ['rights', 'consent', 'withdrawal'],
    displayOrder: 12,
  },
  {
    code: 'PDPL-3.1',
    title: 'Data Breach Notification',
    titleAr: 'الإخطار بخرق البيانات',
    description: 'Controllers must notify SDAIA and affected data subjects of personal data breaches without undue delay.',
    descriptionAr: 'يجب على المتحكمين إخطار سدايا وأصحاب البيانات المتأثرين بخروقات البيانات الشخصية دون تأخير لا مبرر له.',
    category: 'Data Breach Management',
    categoryAr: 'إدارة خروقات البيانات',
    priority: 'critical',
    implementationGuidance: 'Establish incident response procedures and breach notification protocols.',
    implementationGuidanceAr: 'وضع إجراءات الاستجابة للحوادث وبروتوكولات الإخطار بالخروقات.',
    evidenceRequirements: ['Incident Response Plan', 'Breach Notification Procedures'],
    testingProcedures: ['Review incident response plan', 'Test breach notification process'],
    tags: ['breach', 'notification', 'incident-response'],
    displayOrder: 13,
  },
  {
    code: 'PDPL-4.1',
    title: 'Data Protection Impact Assessment (DPIA)',
    titleAr: 'تقييم أثر حماية البيانات',
    description: 'Controllers must conduct DPIAs for high-risk data processing activities.',
    descriptionAr: 'يجب على المتحكمين إجراء تقييمات أثر حماية البيانات لأنشطة المعالجة عالية المخاطر.',
    category: 'Risk Management',
    categoryAr: 'إدارة المخاطر',
    priority: 'high',
    implementationGuidance: 'Identify high-risk processing activities and conduct comprehensive DPIAs.',
    implementationGuidanceAr: 'تحديد أنشطة المعالجة عالية المخاطر وإجراء تقييمات أثر شاملة.',
    evidenceRequirements: ['DPIA Reports', 'Risk Assessment Documentation'],
    testingProcedures: ['Review DPIA process', 'Verify high-risk activities are assessed'],
    tags: ['dpia', 'risk-assessment', 'privacy'],
    displayOrder: 14,
  },
  {
    code: 'PDPL-5.1',
    title: 'Data Processing Agreements',
    titleAr: 'اتفاقيات معالجة البيانات',
    description: 'Controllers must have written agreements with processors defining data processing obligations.',
    descriptionAr: 'يجب أن يكون لدى المتحكمين اتفاقيات مكتوبة مع المعالجين تحدد التزامات معالجة البيانات.',
    category: 'Third-Party Management',
    categoryAr: 'إدارة الأطراف الثالثة',
    priority: 'high',
    implementationGuidance: 'Draft and sign data processing agreements with all third-party processors.',
    implementationGuidanceAr: 'صياغة وتوقيع اتفاقيات معالجة البيانات مع جميع المعالجين من الأطراف الثالثة.',
    evidenceRequirements: ['Data Processing Agreements', 'Vendor Contracts'],
    testingProcedures: ['Review DPA terms', 'Verify all processors have agreements'],
    tags: ['dpa', 'third-party', 'contracts'],
    displayOrder: 15,
  },
];

/**
 * ملاحظة: هذا ملف seed data أولي يحتوي على:
 * - 7 أطر تنظيمية رئيسية
 * - 15 ضابط من نظام PDPL كمثال
 * 
 * سيتم إضافة المزيد من الضوابط للأطر الأخرى (ECC, AML/CFT, إلخ) في ملفات منفصلة
 * لتسهيل الصيانة والتحديث.
 */
